### ISSUE TITLE
Request for the weight of Q-networks

### ISSUE THREAD

**Issue by ResearcherYan** [MatthewChang/video-dqn#40]
Hi Dr. Chang. Thanks for the solid work you guys did. I want to build upon your great work to take a further step in the ObjectNav task. Could you please generously provide the weight of Q-networks in the original paper?

I've tried to get in touch with you through email, but not sure if your UIUC email is still in use since you've already got the PhD degree. So I raise an issue here to make the request again. Thanks a lot!

**Comment by MatthewChang** [comment]
The weights should be automatically downloaded when you evaluate with the pretrained config (see the readme) `SCENE_GRAPH_LOCATION_TINY=[3d_scene_graph_tiny_annotations_location] GIBSON_LOCATION=[gibson_path] python ./evaluation/runner.py evaluation/config_pretrained.yml -g [GPU_ID]`

If you're having a hard time running this due to habitat version issues etc the weights are available here [here](http://matthewchang.web.illinois.edu/data/vlv_model.torch)

**Comment by ResearcherYan** [comment]
OK, I got it. Thank you, Dr. Chang!
